"""changes field short

Revision ID: d87380265cf4
Revises: f0a79e33dc62
Create Date: 2024-12-02 16:07:48.875950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87380265cf4'
down_revision = 'f0a79e33dc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
