"""change short, nullable True

Revision ID: f0a79e33dc62
Revises: 01ecb491cd43
Create Date: 2024-11-28 12:14:51.185805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a79e33dc62'
down_revision = '01ecb491cd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###
